/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceTimekeepingRouteImport } from './routes/_workspace/timekeeping'
import { Route as WorkspaceShiftsRouteImport } from './routes/_workspace/shifts'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceTimekeepingRoute = WorkspaceTimekeepingRouteImport.update({
  id: '/timekeeping',
  path: '/timekeeping',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceShiftsRoute = WorkspaceShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/shifts': typeof WorkspaceShiftsRoute
  '/timekeeping': typeof WorkspaceTimekeepingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/shifts': typeof WorkspaceShiftsRoute
  '/timekeeping': typeof WorkspaceTimekeepingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/shifts': typeof WorkspaceShiftsRoute
  '/_workspace/timekeeping': typeof WorkspaceTimekeepingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/shifts' | '/timekeeping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/shifts' | '/timekeeping'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/_workspace/dashboard'
    | '/_workspace/shifts'
    | '/_workspace/timekeeping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/timekeeping': {
      id: '/_workspace/timekeeping'
      path: '/timekeeping'
      fullPath: '/timekeeping'
      preLoaderRoute: typeof WorkspaceTimekeepingRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/shifts': {
      id: '/_workspace/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof WorkspaceShiftsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceShiftsRoute: typeof WorkspaceShiftsRoute
  WorkspaceTimekeepingRoute: typeof WorkspaceTimekeepingRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceShiftsRoute: WorkspaceShiftsRoute,
  WorkspaceTimekeepingRoute: WorkspaceTimekeepingRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
